//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testik
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorzinaOfTovari
    {
        public int idCorzina { get; set; }
        public int idTovari { get; set; }
        public Nullable<int> Quntity { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Corzina Corzina { get; set; }
        public virtual Tovari Tovari { get; set; }
    }
}
